from typing import Protocol


class IProjectLockManager(Protocol):
    def acquire_lock(self, project_id: str, ttl_seconds: int = 3600) -> bool: ...

    def release_lock(self, project_id: str) -> None: ...

    def is_locked(self, project_id: str) -> bool: ...

    def extend_lock(self, project_id: str, ttl_seconds: int) -> bool: ...
