from typing import Protocol


class ISessionStorage(Protocol):
    def save_session_id(self, user_id: int, session_id: str) -> None: ...
    def get_session_id(self, user_id: int) -> str | None: ...
    def clear_session_id(self, user_id: int) -> None: ...
